#pragma once
// ============================================================
// FP-SAN Phase 4: METAMORPHIC AGENCY
//
// JARVIS can author and hot-load new motor primitives at runtime:
//   1. Read own source header to understand existing API shape.
//   2. Generate minimal C++ source for a new MotorAction handler.
//   3. Invoke cl.exe to compile a .dll from the generated source.
//   4. LoadLibrary() the .dll under a brief unique_lock.
//   5. Register the new primitive in the graph via EDGE_IMPLEMENTED_BY.
//
// The hot-swap is locked with unique_lock for < 5ms (same as sleep).
// After loading, the new primitive survives sleep/wake cycles because
// the graph persists its node + EDGE_IMPLEMENTED_BY topology.
// ============================================================

#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <shared_mutex>
#include "cluster_graph.h"
#include "fpsan_language.h"
#include "fpsan_self_edit_registry.h"

// Exported function signature for hot-loaded motor primitives.
// A loaded .dll must export this function:
//   extern "C" __declspec(dllexport) void fpsan_motor_init(void* graph_ptr, void* cortex_ptr);
using FpsanMotorInitFn = void(*)(void*, void*);

// ── Code template for a generated motor primitive ──────────────
// The generated file is a minimal DLL that exports fpsan_motor_init().
// It spawns a graph node with MOTOR_SLEEP_MS (as a safe stub) and
// wires it under the concept_word via EDGE_IMPLEMENTED_BY.
static const char* METAMORPHIC_TEMPLATE = R"(
// AUTO-GENERATED by FP-SAN Metamorphic Agency — DO NOT EDIT
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdio>

// Forward-declare the MotorActionType and EDGE_IMPLEMENTED_BY integer values
// so the DLL can call back into the host without linking fpsan headers.
// We use raw integers to avoid ABI coupling.
enum { _MOTOR_SLEEP_MS = 7, _EDGE_IMPLEMENTED_BY = 14 };

// Host ABI: these functions are called via function pointer passed at init.
typedef int  (*SpawnFn)(void* graph);
typedef void (*AddEdgeFn)(void* graph, int src, int dst, float w, int etype);
typedef void (*SetMotorFn)(void* graph, int node_id, int type, int delay_ms);

extern "C" __declspec(dllexport)
void fpsan_motor_init(void* spawn_fn, void* add_edge_fn, void* set_motor_fn,
                      void* graph_ptr, int concept_id) {
    auto spawn    = reinterpret_cast<SpawnFn>(spawn_fn);
    auto add_edge = reinterpret_cast<AddEdgeFn>(add_edge_fn);
    auto set_motor= reinterpret_cast<SetMotorFn>(set_motor_fn);
    int m_id = spawn(graph_ptr);
    if (m_id < 0) return;
    set_motor(graph_ptr, m_id, _MOTOR_SLEEP_MS, 42);  // stub: sleep 42ms
    add_edge(graph_ptr, concept_id, m_id, 2.0f, _EDGE_IMPLEMENTED_BY);
    printf("[MetamorphicPrimitive] Registered motor node %d for concept %d.\n", m_id, concept_id);
}
)";

// ── Host-side callbacks exposed to the DLL (plain C ABI) ──────
inline bool metamorphic_artefact_file_size_bytes(const char* path, uint64_t* out) noexcept {
    if (!path || !out) return false;
    WIN32_FILE_ATTRIBUTE_DATA fad{};
    if (!GetFileAttributesExA(path, GetFileExInfoStandard, &fad)) return false;
    ULARGE_INTEGER uli;
    uli.HighPart = fad.nFileSizeHigh;
    uli.LowPart = fad.nFileSizeLow;
    *out = uli.QuadPart;
    return true;
}

extern "C" {
    static int _meta_spawn(void* g) {
        return reinterpret_cast<ClusterGraph*>(g)->spawn();
    }
    static void _meta_add_edge(void* g, int src, int dst, float w, int etype) {
        reinterpret_cast<ClusterGraph*>(g)->node(src).add_edge(dst, w, (EdgeType)etype);
    }
    static void _meta_set_motor(void* g, int node_id, int type, int delay_ms) {
        ClusterGraph* graph = reinterpret_cast<ClusterGraph*>(g);
        graph->node(node_id).is_motor_node.store(true, std::memory_order_release);
        graph->node(node_id).motor_action.type     = (MotorActionType)type;
        graph->node(node_id).motor_action.delay_ms = delay_ms;
    }
}

// ============================================================
// METAMORPHIC ENGINE
// ============================================================
struct MetamorphicEngine {
    HMODULE loaded_dll = nullptr;
    char    dll_path[MAX_PATH];
    char    src_path[MAX_PATH];

    // Generate, compile, and hot-load a new motor primitive.
    // concept_word: the concept node this primitive implements.
    // concept_id:   the graph node ID of the concept.
    // cl_exe:       path to cl.exe (e.g. "cl.exe" if in PATH).
    // Returns true on success, false on failure.
    bool hot_load(const char* concept_word, int concept_id,
                  ClusterGraph* graph, LanguageCortex* cortex,
                  std::shared_mutex& rw_lock,
                  const char* cl_exe = "cl.exe",
                  const char* build_dir = "build",
                  fpsan::SelfEditRegistry* self_edit_reg = nullptr,
                  uint64_t episode_now = 0) {
        // 1. Write generated source file
        snprintf(src_path, MAX_PATH, "%s\\meta_%s.cpp", build_dir, concept_word);
        snprintf(dll_path, MAX_PATH, "%s\\meta_%s.dll", build_dir, concept_word);

        FILE* f = fopen(src_path, "w");
        if (!f) {
            printf("[Metamorphic] ERROR: Cannot write source to %s\n", src_path);
            return false;
        }
        fputs(METAMORPHIC_TEMPLATE, f);
        fclose(f);
        printf("[Metamorphic] Generated source: %s\n", src_path);

        // 2. Invoke cl.exe to compile the .dll
        char cmd[1024];
        snprintf(cmd, sizeof(cmd),
            "%s /LD /nologo /O2 /EHsc \"%s\" /Fe:\"%s\" 2>&1",
            cl_exe, src_path, dll_path);

        printf("[Metamorphic] Compiling: %s\n", cmd);
        int ret = system(cmd);
        if (ret != 0) {
            printf("[Metamorphic] ERROR: Compilation failed (exit=%d).\n", ret);
            return false;
        }
        printf("[Metamorphic] Compiled: %s\n", dll_path);

        // 3. Hot-load under unique_lock (brief, like sleep cycle)
        {
            std::unique_lock<std::shared_mutex> lk(rw_lock);

            // Unload any previously loaded version
            if (loaded_dll) {
                FreeLibrary(loaded_dll);
                loaded_dll = nullptr;
            }

            loaded_dll = LoadLibraryA(dll_path);
            if (!loaded_dll) {
                printf("[Metamorphic] ERROR: LoadLibrary failed (error=%lu).\n",
                       GetLastError());
                return false;
            }

            uint64_t dll_bytes = 0;
            (void)metamorphic_artefact_file_size_bytes(dll_path, &dll_bytes);
            if (self_edit_reg) {
                if (!self_edit_reg->register_or_touch(dll_path, "dll", episode_now,
                                                       dll_bytes, false)) {
                    printf("[Metamorphic] ERROR: Self-edit registry rejected artefact "
                           "(%s, %llu bytes) — exceeds cap or budget.\n",
                           dll_path, (unsigned long long)dll_bytes);
                    FreeLibrary(loaded_dll);
                    loaded_dll = nullptr;
                    DeleteFileA(dll_path);
                    return false;
                }
            }

            // Resolve exported init function
            auto init_fn = reinterpret_cast<void(*)(void*, void*, void*, void*, int)>(
                GetProcAddress(loaded_dll, "fpsan_motor_init"));
            if (!init_fn) {
                printf("[Metamorphic] ERROR: fpsan_motor_init not found in DLL.\n");
                FreeLibrary(loaded_dll);
                loaded_dll = nullptr;
                return false;
            }

            // Call init with host callbacks
            init_fn((void*)_meta_spawn, (void*)_meta_add_edge,
                    (void*)_meta_set_motor, (void*)graph, concept_id);

            printf("[Metamorphic] Hot-load COMPLETE. Module: %s\n", dll_path);
        } // unique_lock released here

        return true;
    }

    // Check if a DLL is currently loaded.
    bool is_loaded() const noexcept { return loaded_dll != nullptr; }

    ~MetamorphicEngine() {
        if (loaded_dll) {
            FreeLibrary(loaded_dll);
            loaded_dll = nullptr;
        }
    }
};
